#!/bin/sh
VERSION='0.0.1'

. ~/site.conf

search_script=$0
while [ -n "$search_script" ]; do
	entity_script=$search_script
	search_script=$(readlink $search_script)
done
EXECUTE_DIR=$(dirname $entity_script)

# MacやBSDで実行する際にgdateやgsedを使う
if uname -s | grep -sq '\(BSD\|Darwin\)'; then
	export sed_exec='gsed'
	export date_exec='gdate'
else
	export sed_exec='sed'
	export date_exec='date'
fi

while [ $# -gt 0 ]; do
	case $1 in
		version)
			echo "version: $VERSION"
			exit 0
			;;
		new)
			$EXECUTE_DIR/new $2
			exit 0
			;;
		make)
			$EXECUTE_DIR/make $2
			exit 0
			;;
		update)
			$EXECUTE_DIR/update $2
			exit 0
			;;
		send)
			$EXECUTE_DIR/send
			exit 0
			;;
		receive)
			$EXECUTE_DIR/receive
			exit 0
			;;
		remove)
			exit 0
			;;
		preview)
			exit 0
			;;
		*)
			exit 0
			;;
	esac
	shift
done
