#!/bin/sh

eval $(ssh-agent)
trap 'eval $(ssh-agent -k); exit 1' 1 2 3 15
eval ssh-add $SITE_SSH_KEY
echo ""

list=$(ssh $SITE_DOMAIN "ls -U $SITE_ABSOLUTE_PATH$SITE_POSTS_DIR | sort -nr")
echo "$list" | nl

while true; do
	echo ""
	env echo -n '(? for help, q for quit): '
	read select_num
	if echo $select_num | grep -sq '[0-9|,$]'; then
		break
	elif [ "$select_num" = '?' ]; then
		echo ""
		cat <<- EOM
			example(single specification): 1 3 6 9
			example(range specification): 2,5 10,$
		EOM
	elif [ "$select_num" = 'q' ]; then
		eval $(ssh-agent -k)
		exit 0
	fi
done
select_num=$(echo $select_num | $sed_exec 's/\([^ ]*\)/-e \1p/g')
echo ""

echo "$list" | $sed_exec -n $select_num | xargs -I @ rsync -auvz -e ssh $SITE_DOMAIN:$SITE_ABSOLUTE_PATH${SITE_POSTS_DIR}@ $(pwd)/

echo ""
eval $(ssh-agent -k)
exit 0
