#!/bin/sh

eval $(ssh-agent)
trap 'eval $(ssh-agent -k); exit 1' 1 2 3 15
eval ssh-add $SITE_SSH_KEY
echo ""

list=$(ssh $SITE_DOMAIN "ls -U $SITE_ABSOLUTE_PATH$SITE_POSTS_DIR | sort -nr")
echo "$list" | nl

while true; do
	echo ""
	env echo -n '(? for help, q for quit): '
	read select_num
	if echo $select_num | grep -sq '[0-9|,$]'; then
		break
	elif [ "$select_num" = '?' ]; then
		echo ""
		cat <<- EOM
			example(single specification): 1 3 6 9
			example(range specification): 2,5 10,$
		EOM
	elif [ "$select_num" = 'q' ]; then
		eval $(ssh-agent -k)
		exit 0
	fi
done
select_num=$(echo $select_num | $sed_exec 's/\([^ ]*\)/-e \1p/g')
select_list=$(echo "$list" | $sed_exec -n $select_num)
echo ""

ssh $SITE_DOMAIN "
	cd $SITE_ABSOLUTE_PATH
	for post in \$(echo \""$select_list"\"); do
		git rm -r ${SITE_POSTS_DIR}/\$post
		git commit -m \"\$post: deleted\"
	done
	git ls-remote origin --exit-code 1 > /dev/null 2>&1
	if [ \"\$?\" -eq 0 ]; then
		git push origin master
	fi"
eval $(ssh-agent -k)

echo ""
exit 0
