#!/bin/sh
. ~/site.conf

list=$(
	ls -U $(pwd)                            |
	find -mindepth 1 -maxdepth 2 -name html |
	cut -d '/' -f 2                         |
	sort -nr)

if [ -z "$list" ]; then
	echo 'no such article in this directory.'
	exit 1
fi

echo ""
echo "$list" | nl
while true; do
	echo ""
	env echo -n '(? for help, q for quit): '
	read select_num
	if echo $select_num | grep -sq '[0-9|,$]'; then
		break
	elif [ $select_num = 'q' ]; then
		exit 0
	fi
	echo ""
	cat <<- EOM
	  example(single specification): 1 3 6 9
	  example(range specification): 2,5 10,$
	EOM
done
select_num=$(echo $select_num | $sed_exec 's/\([^ ]*\)/-e \1p/g')
echo ""

eval $(ssh-agent)
trap 'eval $(ssh-agent -k); exit 1' 1 2 3 15
ssh-add ~/.ssh/id_rsa
echo "$list" | $sed_exec -n $select_num | xargs -I @ rsync -auvz --delete -e ssh $(pwd)/@ $SITE_DOMAIN:$SITE_ABSOLUTE_PATH${SITE_POSTS_DIR}
ssh $SITE_DOMAIN "cd $SITE_ABSOLUTE_PATH; ./make_archives.dash; ./make_labels.dash; ./make_search_cache.dash"
eval $(ssh-agent -k)

echo ""
exit 0
