#!/bin/sh
VERSION='0.0.1'

if [ ! -d ~/.site ]; then
	mkdir ~/.site
fi
cd ~/.site

current_conf() {
	. ./site.conf
	echo ""
	echo "current selected site: $SITE_URL"
}

generate_conf() {
	env echo -n 'url: '
	read url
	env echo -n 'ssh: '
	read ssh
	env echo -n 'key: '
	read key
	env echo -n 'server path: '
	read path
	env echo -n "post dir: $path"
	read postdir
	cat <<- + > $1
		export SITE_URL="$url"
		export SITE_DOMAIN="$ssh"
		export SITE_SSH_KEY="$key"
		export SITE_ABSOLUTE_PATH="$path"
		export SITE_POSTS_DIR="$postdir"
	+
}

list_conf() {
	number=1
	list=$(
		echo "number url hostname key path postdir"
		while [ -f ${number}.conf ]; do
			. ./${number}.conf
			echo "$number $SITE_URL $SITE_DOMAIN $SITE_SSH_KEY $SITE_ABSOLUTE_PATH $SITE_POSTS_DIR"
			number=$(($number + 1))
		done)
	if [ $(echo "$list" | wc -l) = 1 ]; then
		echo 'please configure any site'
		exit 1
	fi
	echo "$list" | column -t
}

select_conf() {
	list_conf
	while true; do
	env echo -n "select $1 site of number: "
	read number
		if [ $number = 'q' ]; then
			exit 0
		elif ! echo $number | grep -sqE '^[0-9]+$'; then
			echo 'wrong number'
		elif [ ! -f ${number}.conf ]; then
			echo 'wrong number'
		else
			break
		fi
	done
}

add() {
	new_number=1
	while [ -f ${new_number}.conf ]; do
		new_number=$(($new_number + 1))
	done
	new_conf=${new_number}.conf
	generate_conf $new_conf
	if [ ! -f site.conf ]; then
		ln -s $new_conf site.conf
	fi
	current_conf
}

show() {
	list_conf
	current_conf
}

edit() {
	select_conf edit
	generate_conf ${number}.conf
	current_conf
}

switch() {
	select_conf switch
	ln -sf ${number}.conf site.conf
	current_conf
}

remove() {
	select_conf remove
	rm ${number}.conf
	while [ -f $(($number + 1)).conf ]; do
		mv $(($number + 1)).conf ${number}.conf
	done
	rm site.conf
	if [ -f 1.conf ]; then
		echo ""
		switch
	fi
}

while [ $# -gt 0 ]; do
	case $1 in
		version)
			echo "version: $VERSION"
			exit 0
			;;
		add)
			add
			exit 0
			;;
		show)
			show
			exit 0
			;;
		edit)
			edit
			exit 0
			;;
		switch)
			switch
			exit 0
			;;
		remove)
			remove
			exit 0
			;;
		*)
			exit 0
			;;
	esac
	shift
done
